// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClJAvkQ3_wxCkSxsYKWmsSj4c7SRUFn68',
    appId: '1:989427213735:android:116655d38955ad61924282',
    messagingSenderId: '989427213735',
    projectId: 'bessie-camp-app',
    storageBucket: 'bessie-camp-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrv552i5vl1jyL4Tx6eA3A1lxoXmwJIhA',
    appId: '1:989427213735:ios:8053801d7f80281b924282',
    messagingSenderId: '989427213735',
    projectId: 'bessie-camp-app',
    storageBucket: 'bessie-camp-app.firebasestorage.app',
    iosBundleId: 'com.bessie.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrv552i5vl1jyL4Tx6eA3A1lxoXmwJIhA',
    appId: '1:989427213735:ios:8053801d7f80281b924282',
    messagingSenderId: '989427213735',
    projectId: 'bessie-camp-app',
    storageBucket: 'bessie-camp-app.firebasestorage.app',
    iosBundleId: 'com.bessie.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXhEpuH8mkbnk-oyM_Jb5ahnv7hJZd_-4',
    appId: '1:989427213735:web:041079fc7cc74508924282',
    messagingSenderId: '989427213735',
    projectId: 'bessie-camp-app',
    authDomain: 'bessie-camp-app.firebaseapp.com',
    storageBucket: 'bessie-camp-app.firebasestorage.app',
    measurementId: 'G-TRR35FZ4V0',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXhEpuH8mkbnk-oyM_Jb5ahnv7hJZd_-4',
    appId: '1:989427213735:web:01bffe7089d68425924282',
    messagingSenderId: '989427213735',
    projectId: 'bessie-camp-app',
    authDomain: 'bessie-camp-app.firebaseapp.com',
    storageBucket: 'bessie-camp-app.firebasestorage.app',
    measurementId: 'G-8E9QX5JBCT',
  );

}