name: bessie
description: "Camp logistics manager"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ember_core:
    path: ../ember_core

  # UI
  shadcn_ui: ^0.20.3

  # Utility Packages
  intl: ^0.19.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  image_picker: ^1.1.0
  url_launcher: ^6.2.6
  flutter_dropzone: ^4.2.1
  flutter_typeahead: ^5.2.0
  connectivity_plus: ^6.0.3
  multi_select_flutter: ^4.1.3
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  uuid: ^3.0.7
  csv: ^5.0.0
  window_manager: ^0.2.7
  synchronized: ^3.0.0
  pdf: ^3.11.1
  file_picker: ^9.0.2

  # Web Specific
  # web: ^0.5.1
  # http: ^1.2.1
  # html: ^0.15.4
  # fl_chart: ^0.67.0
  # url_strategy: ^0.2.0
  # universal_html: ^2.2.4

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1



  rxdart: ^0.27.0

  # Random Shit
  xterm: ^4.0.0
  http: any # dart fix says I need this
  visibility_detector: ^0.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true


  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_24pt-Italic.ttf
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_28pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_24pt-Black.ttf
          weight: 900

    - family: FiraCodeMono
      fonts:
        - asset: assets/fonts/fira_code_mono/FiraCodeNerdFontMono-Retina.ttf
          weight: 400