name: bess_ui
description: "Camp logistics manager frontend"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ember_core:
    path: ../ember_core

  ember_cli_utils:
    path: ../ember_cli_utils

  # UI
  shadcn_ui: ^0.26.5

  # Utility Packages
  lottie: ^3.3.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  window_manager: ^0.4.3
  rxdart: ^0.28.0
  xterm: ^4.0.0
  ansicolor: ^2.0.3
  data_table_2: ^2.6.0
  device_info_plus: ^11.5.0

  # Web Specific
  web: ^1.1.1

  # State Management
  get: ^4.7.2

  sentry_flutter: ^8.14.2


dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

