import 'dart:math';

import 'package:intl/intl.dart';

import '../data_models/analogs/algo_period.dart';
import '../data_models/assignment_context.dart';
import '../data_models/assignment_result.dart';
import '../data_models/interfaces/algorithm_step.dart';
import '../data_models/pipeline_state.dart';
import '../data_models/potential_assignment.dart';
import '../evaluation/step_report.dart';

/// The second step in the pipeline, responsible for scoring assignments.
///
/// This step iterates through each `PotentialAssignment` generated by the previous
/// step and calculates a numerical score, which is then attached to the assignment
/// object itself. The scoring logic is based on preference, age, and repetition.
class ScoreAssignmentsStep extends AlgorithmStep {
  // --- Preference Tiers ---
  /// The score for a participant's most desired activities ("Golden Ticket").
  static const double goldenTicketBonus = 100.0;

  /// The score for activities a participant is highly interested in.
  static const double highInterestBonus = 50.0;

  /// The score for activities a participant is neutral or curious about.
  static const double flexibleChoiceBonus = 10.0;

  /// The penalty for activities a participant has low interest in.
  static const double lowInterestPenalty = -20.0;

  /// A penalty so severe it effectively blocks an assignment.
  static const double hardNoPenalty = -1000.0;

  // --- Age-Based Weighting (Now with a Curve) ---
  /// The maximum bonus a participant can receive based on their age.
  static const double youngerParticipantMaxBonus = 20.0;

  /// The age at which participants start receiving the age bonus.
  static const int youngerParticipantMinAge = 8;

  /// The age at which the age bonus becomes zero.
  static const int youngerParticipantMaxAge = 13;


  // --- Repetition Penalties ---
  /// The base penalty for being assigned to the same activity more than once on the same day.
  /// This penalty decays with distance.
  static const double baseRepetitionPenalty = -50.0;

  /// A harsh penalty for being assigned to the same activity in an adjacent time block.
  /// This is now primarily for the hard constraint but can be used as a score too.
  static const double adjacentRepetitionPenalty = -100.0;

  /// A factor (0.0 to 1.0) by which the repetition penalty is reduced for each
  /// block separating two assignments.
  /// e.g., 0.5 means the penalty is halved for each intervening block.
  static const double repetitionPenaltyDecayFactor = 0.6;
  
  @override
  String get stepName => 'Score Assignments';

  @override
  StepReport execute(PipelineState state) {
    // Go through every potential assignment...
    for (final PotentialAssignment potentialAssignment in state.potentialAssignments) {
      // ...and calculate its score, modifying the object directly.
      potentialAssignment.score = _calculateScore(potentialAssignment, state.context, state.result);
    }

    return StepReport(
      stepName: stepName,
      summary: 'Calculated scores for ${state.potentialAssignments.length} assignments.',
      details: {'count': state.potentialAssignments.length},
      duration: Duration.zero,
    );
  }

  /// Calculates the total score for a potential assignment based on multiple factors.
  double _calculateScore(PotentialAssignment assignment, AssignmentContext context, AssignmentResult result) {
    double totalScore = 0.0;
    // 1. Add points based on participant's interest.
    totalScore += _getPreferenceBonus(assignment, context);
    // 2. Add points if the participant is young.
    totalScore += _calculateAgeBonus(assignment.participant.birthdate);
    // 3. Subtract points for repeating an activity on the same day.
    totalScore += _getRepetitionPenalty(assignment, context, result);
    return totalScore;
  }

  /// Calculates a score bonus or penalty based on a participant's stated preference.
  double _getPreferenceBonus(PotentialAssignment assignment, AssignmentContext context) {
    // Looks up the preference value (e.g., 0.0 to 1.0). Defaults to 0.5 (neutral).
    final preference = context.participantPreferences[assignment.participant.id]?[assignment.activity.id] ?? 0.5;
    // Returns a score based on predefined tiers.
    if (preference >= 0.9) return goldenTicketBonus;
    if (preference >= 0.7) return highInterestBonus;
    if (preference >= 0.3) return flexibleChoiceBonus;
    if (preference >= 0.1) return lowInterestPenalty;
    return hardNoPenalty;
  }

  /// Calculates a penalty for assigning the same activity too close together.
  double _getRepetitionPenalty(PotentialAssignment currentAssignment, AssignmentContext context, AssignmentResult result) {
    double totalPenalty = 0.0;
    final participantId = currentAssignment.participant.id;
    final activityId = currentAssignment.activity.id;

    // Check against all assignments made so far.
    final allAssignments = [
      ...context.getAssignmentsForParticipant(participantId),
      ...result.getAssignmentsForParticipant(participantId),
    ];

    for (final otherAssignment in allAssignments) {
      if (otherAssignment.activity.id == activityId) {
        // Calculate how many periods are between the two assignments on the same day.
        final distance = _calculatePeriodDistance(currentAssignment.period, otherAssignment.period, context.weeklyPeriodsSorted);

        // If they are on the same day (distance != -1)...
        if (distance != -1) {
          // ...apply a penalty that shrinks as the distance grows.
          final decay = pow(repetitionPenaltyDecayFactor, distance);
          totalPenalty += (baseRepetitionPenalty * decay);
        }
      }
    }
    return totalPenalty;
  }

  /// Calculates an age-based bonus using a linear sliding scale.
  double _calculateAgeBonus(DateTime birthdate) {
    // Simple age calculation.
    final now = DateTime.now();
    int age = now.year - birthdate.year;
    if (now.month < birthdate.month || (now.month == birthdate.month && now.day < birthdate.day)) {
      age--;
    }

    // Participants below a min age get the max bonus.
    if (age <= youngerParticipantMinAge) {
      return youngerParticipantMaxBonus;
    }
    // Participants above a max age get no bonus.
    if (age >= youngerParticipantMaxAge) {
      return 0.0;
    }

    // For ages in between, calculate a bonus that decreases as age increases.
    final ageRange =
        (youngerParticipantMaxAge - youngerParticipantMinAge)
            .toDouble();
    final participantPositionInRange = (age - youngerParticipantMinAge).toDouble();
    final bonus = youngerParticipantMaxBonus * (1 - (participantPositionInRange / ageRange));
    return max(0.0, bonus);
  }

  int _calculatePeriodDistance(AlgoPeriod periodA, AlgoPeriod periodB, List<AlgoPeriod> weeklyPeriodsSorted) {
    final DateFormat formatter = DateFormat('yyyy-MM-dd');
    final dayA = formatter.format(periodA.start);
    final dayB = formatter.format(periodB.start);

    if (dayA != dayB) return -1; // -1 signifies different days

    final indexA = weeklyPeriodsSorted.indexWhere((p) => p.id == periodA.id);
    final indexB = weeklyPeriodsSorted.indexWhere((p) => p.id == periodB.id);

    if (indexA == -1 || indexB == -1) return -1;

    // The distance is the number of periods *between* the two.
    return (indexA - indexB).abs() - 1;
  }
}
