name: ember_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  ember_fire:
    path: ../ember_fire

  # State Management
  get: ^4.7.2

  # Utility Packages
  intl: any
  pdf: ^3.11.3
  file_picker: ^10.0.0
  csv: ^6.0.0


dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
