name: ember_core
description: A starting point for Dart libraries or applications.
version: 0.1.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

dependencies:
  ember_cli_utils:
    path: ../ember_cli_utils

  # State Management
  get: ^4.7.2

  # Utility Packages
  intl: any
  pdf: ^3.11.3
  file_picker: ^10.2.0
  csv: ^6.0.0
  logger: ^2.6.0
  shared_preferences: ^2.5.3
  collection: ^1.19.1

  # Firebase
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_crashlytics: ^4.3.7
  firebase_analytics: ^11.5.0
  firebase_auth: ^5.6.0


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.15
