name: bessie
description: Application runner for the Bessie project.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter/Dart packages used in main.dart
  flutter_native_splash: ^2.4.6
  get: ^4.7.2
  window_manager: ^0.4.3
  firebase_core: ^3.13.0
  sentry_flutter: ^8.14.2

  # --- Local Monorepo Packages ---
  bess_ui:
    path: ../../packages/bess_ui
  ember_core:
    path: ../../packages/ember_core
  ember_fire:
    path: ../../packages/ember_fire

dev_dependencies:
  lints: ^5.1.1

flutter:
  uses-material-design: true

flutter_native_splash:
  # dart run flutter_native_splash:create

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.
  color: "#eff1f5"
  #background_image: "assets/background.png"

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/logos/splash-logo.png

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. It is supported for Android, iOS and the Web.  For Android 12,
  # see the Android 12 section below.
  # branding: assets/logos/ember-core-branding.png

  # Set the branding padding from the bottom of the screen.  The default value is 0
  # (Not supported on web yet)
  # branding_bottom_padding: 24

  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode.
  # color_dark and background_image_dark cannot both be set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png

  android_12:
    color: "#eff1f5"
    image: assets/logos/splash-logo.png
    branding: assets/logos/ember-core-branding.png
    branding_bottom_padding: 24

  fullscreen: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - logos/
    - images/content/
    - images/animations/
  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_24pt-Italic.ttf
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_28pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_24pt-Black.ttf
          weight: 900

    - family: FiraCodeMono
      fonts:
        - asset: assets/fonts/fira_code_mono/FiraCodeNerdFontMono-Retina.ttf
          weight: 400

